#%RAML 1.0
title: "HMIS User Service"
version: "1.0.0"
protocols:
- "HTTPS"
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
baseUri: "https://www.hmislynk.com/hmis-user-service/rest"
/accounts:
  description: "All accounts"
  post:
    description: "It creates an account with the specified username and sends out\
      \ an email to the user to verify the account creation. The initial status of\
      \ the newly created account is PENDING. The status is changed to ACTIVE when\
      \ the user verifies account creation by clicking the link embedded in the email.\
      \ Only an ACTIVE account can log-in using the Create a session (Log-in) API.\
      \ <br> It returns an error if an account with the specified username already\
      \ exists.\nThis endpoint does the following:\n1) If request does not contain\
      \ profile information, standard profile will be assigned to the user.\n2) If\
      \ request does not contain role information, default role will be assigned based\
      \ on profile.    \n3) Project Group of the user will be same as the project\
      \ group of logged-in user who creates the account.\nThe user must have \"USR_CREATE_ACCOUNT\"\
      \ permission to use this API    \n"
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    body:
      application/json:
        example: |
          {
              "account":{
                      "firstName":"First Name",
                      "lastName":"Last Name",
                      "middleName":"Middle Name",
                      "username":"hslynkuser@gmail.com",
                      "password":"hSLynk",
                      "confirmPassword":"hSLynk",
                      "emailAddress":"hslynkuser@gmail.com",
                      "profile":{
                       "id":"004aed07-b4d4-4696-b8f6-1607f6f49bac"
                      }
              }
          }
    responses:
      200:
        body:
          application/json:
           example: |
             {
                      "account":{
                      "accountId":"a1e8218c-0c4a-49a4-84e7-0b8f521488f1",
                      "username":"hslynkuser@gmail.com",
                      "emailAddress":"hslynkuser@gmail.com",
                      "firstName":"First Name",
                      "middleName":"Middle Name",
                      "lastName":"Last Name",
                      "gender":0,
                      "status":"PENDING",
                      "twoFactorAuthentication":false,
                      "projectGroup":{
                              "projectGroupName":"PROJECT_GROUP_NAME",
                              "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION",
                              "projectGroupId":"9b9792ca-8730-4d21-9a39-6902229fd4b9",
                              "projectGroupCode":"PG0001",
                              "skipuseridentifers":false,
                              "bucketName":"pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9",
                              "senderEmail":"support@hmislynk.com",
                              "projects":[

                              ]
                      },
                      "profile":{
                              "profileName":"Standard Profile",
                              "profileDescription":"Standard Profile",
                              "apiMethods":[

                              ],
                              "id":"004aed07-b4d4-4696-b8f6-1607f6f49bac"
                              },
                      "roles":[

                      ]
                      }
                      }
      409:
        description: "An account with the specified username already exists."
        body:
          application/json:
            type: "object"
  get:
    description: "To get all the users under logged in your project group."
    queryParameters:
      startIndex:
        type: "string"
        default: "0"
        required: false
      maxItems:
        type: "string"
        default: "30"
        required: false
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
           example: |
                   {
                     "accounts":{
                        "pagination":{
                           "from":0,
                           "maximum":30,
                           "total":50,
                           "returned":2,
                           "sort":{

                           }
                        },
                        "account":[
                           {
                              "accountId":"d5038a87-1f32-4269-8bca-9c4fa4901d4a",
                              "username":"custadmin@gmail.com",
                              "emailAddress":"custadmin@gmail.com",
                              "firstName":"Test",
                              "middleName":"Middle Name",
                              "lastName":"Last Name",
                              "gender":0,
                              "status":"ACTIVE",
                              "twoFactorAuthentication":false,
                              "projectGroup":{
                                 "projectGroupName":"PROJECT_GROUP_NAME",
                                 "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION",
                                 "projectGroupId":"9b9792ca-8730-4d21-9a39-6902229fd4b9",
                                 "projectGroupCode":"PG0001",
                                 "skipuseridentifers":false,
                                 "bucketName":"pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9",
                                 "senderEmail":"mc211_support@ctagroup.org",
                                 "projects":[

                                 ]
                              },
                              "profile":{
                                 "profileName":"Customer Admin Profile",
                                 "profileDescription":"Customer Admin Profile",
                                 "apiMethods":[

                                 ],
                                 "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                              },
                              "roles":[
                                 {
                                    "id":"b67c38a1-2762-4393-b69b-41a0a11e6efd",
                                    "roleName":"CUSTADMIN",
                                    "roleDescription":"Customer Admin Role"
                                 }
                              ]
                           },
                           {
                              "accountId":"54913ffb-2f59-48f7-bd63-ef9e54138beb",
                              "username":"standuser@gmail.com",
                              "emailAddress":"custadmin@gmail.com",
                              "firstName":"Test",
                              "middleName":"Middle Name",
                              "lastName":"Last Name",
                              "gender":0,
                              "status":"PENDING",
                              "twoFactorAuthentication":false,
                              "projectGroup":{
                                 "projectGroupName":"PROJECT_GROUP_NAME",
                                 "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION",
                                 "projectGroupId":"9b9792ca-8730-4d21-9a39-6902229fd4b9",
                                 "projectGroupCode":"PG0001",
                                 "skipuseridentifers":false,
                                 "bucketName":"pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9",
                                 "senderEmail":"mc211_support@ctagroup.org",
                                 "projects":[

                                 ]
                              },
                              "profile":{
                                 "profileName":"Customer Admin Profile",
                                 "profileDescription":"Customer Admin Profile",
                                 "apiMethods":[

                                 ],
                                 "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                              },
                              "roles":[
                                 {
                                    "id":"b67c38a1-2762-4393-b69b-41a0a11e6efd",
                                    "roleName":"CUSTADMIN",
                                    "roleDescription":"Customer Admin Role"
                                 }
                              ]
                           }
                        ]
                     }
                     }
  /{accountid}:
    uriParameters:
      accountid:
        type: "string"
    put:
      description: "To update a specific account information.\nProvide account id as\
        \ path variable for upatading non loggedin user. If need to update logged in\
        \ user send self as account id.\n"
      body:
        application/json:
          example: |
                {
                  "account":{
                     "firstName":"First Name",
                     "lastName":"Last Name",
                     "middleName":"Middle Name",
                     "emailAddress":"custadmin@gmail.com",
                     "profile":{
                        "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                     }
                  }
                }
      responses:
        200:
          body:
            application/json:
             example: |
                   {
                     "account":{
                        "firstName":"First Name",
                        "lastName":"Last Name",
                        "middleName":"Middle Name",
                        "emailAddress":"custadmin@gmail.com",
                        "profile":{
                           "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                        }
                     }
                   }
    get:
      description: "Gets (aka reads or retrieves) a specific account. <BR><br>\nGET\
        \ /accounts/{username}\n<b>\n"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          description: "Successfully retrieved resource(s)\n"
          body:
            application/json:
              example: |
                  {
                     "account":{
                        "accountId":"8b6c6ef2-87c7-47f0-8874-4cca6f09367c",
                        "username":"developeradmin@hmis.com",
                        "emailAddress":"hmisprojects@gmail.com",
                        "firstName":"Developer Admin",
                        "middleName":"Developer Admin",
                        "lastName":"Developer Admin",
                        "gender":0,
                        "status":"ACTIVE",
                        "twoFactorAuthentication":false,
                        "projectGroup":{
                           "projectGroupName":"PROJECT_GROUP_NAME",
                           "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION",
                           "projectGroupId":"9b9792ca-8730-4d21-9a39-6902229fd4b9",
                           "projectGroupCode":"PG0001",
                           "skipuseridentifers":false,
                           "bucketName":"pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9",
                           "senderEmail":"mc211_support@ctagroup.org",
                           "projects":[

                           ]
                        },
                        "profile":{
                           "profileName":"Super Admin Profile",
                           "profileDescription":"Super Admin Profile",
                           "apiMethods":[

                           ],
                           "id":"b67c38a1-2762-4393-b69b-41a0a11e6efc"
                        },
                        "roles":[
                           {
                              "id":"b67c38a1-2762-4393-b69b-41a0a11e6efc",
                              "roleName":"SUPERADMIN",
                              "roleDescription":"Super Admin Role"
                           },
                           {
                              "id":"6b5857d9-bc16-4706-acde-17be5d530631",
                              "roleName":"STANDARD",
                              "roleDescription":"Standard Role"
                           }
                        ]
                     }
                  }
        404:
          body:
            application/json:
             example: |
                 {
                   "errors":{
                      "error":[
                         {
                            "code":"ACCOUNT_NOT_FOUND",
                            "message":"user not found"
                         }
                      ]
                   }
                  }
    delete:
      description: "Account status will be updated to DELETED. \n"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
    /activate:
      put:
        description: "To reactivate a specified user account\n"
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        responses:
          200:
            body:
              application/json:
                type: "object"
          403:
            body:
              application/json:
                type: "object"
    /basicinfo:
      description: "A specific account"
      get:
        description: "Gets (aka reads or retrieves) a specific account. <BR><br>\nGET\
          \ /accounts/{username}\n<b>\n"
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        responses:
          200:
            description: "Successfully retrieved resource(s)\n"
            body:
              application/json:
                example: |
                        {
                           "account":{
                              "accountId":"d5038a87-1f32-4269-8bca-9c4fa4901d4a",
                              "username":"custadmin@gmail.com",
                              "emailAddress":"custadmin@gmail.com",
                              "firstName":"Test",
                              "middleName":"Middle Name",
                              "lastName":"Last Name",
                              "gender":0,
                              "status":"ACTIVE",
                              "twoFactorAuthentication":false,
                              "projectGroup":{
                                 "projectGroupName":"PROJECT_GROUP_NAME",
                                 "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION",
                                 "projectGroupId":"9b9792ca-8730-4d21-9a39-6902229fd4b9",
                                 "projectGroupCode":"PG0001",
                                 "skipuseridentifers":false,
                                 "bucketName":"pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9",
                                 "senderEmail":"mc211_support@ctagroup.org",
                                 "projects":[

                                 ]
                              },
                              "profile":{
                                 "profileName":"Customer Admin Profile",
                                 "profileDescription":"Customer Admin Profile",
                                 "apiMethods":[

                                 ],
                                 "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                              },
                              "roles":[
                                 {
                                    "id":"b67c38a1-2762-4393-b69b-41a0a11e6efd",
                                    "roleName":"CUSTADMIN",
                                    "roleDescription":"Customer Admin Role"
                                 }
                              ]
                           }
                        }
          403:
            body:
              application/json:
                type: "object"
    /passwordchanges:
      description: "Change password for an account"
      put:
        description: "Changes password for an account. To change the password, the user\
          \ must be logged-in and provide his/her current password.\nThe {username} is\
          \ a value that uniquely identifies an account.\nTo change the password of the\
          \ currently logged-in user, the {username} can be replaced by <b>self</b> keyword\
          \ in the URL as shown below.\n<b>POST</b> /accounts/self/passwordchanges\n"
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        body:
         application/json:
           example: |
                   {
                    	"passwordChange":{
                    		"currentPassword":"password",
                    		"newPassword":"123456789@aA",
                    		"confirmNewPassword":"123456789@aA"
                    	}
                    }

        responses:
          200:
            description: ""
            body:
              application/json:
               example: |
                       {
                         "passwordChange":{

                         }
                        }
          403:
            body:
              application/json:
               example: |
                       {
                         "errors":{
                            "error":[
                               {
                                  "code":"ERR_CODE_INVALID_CURRENT_PASSWORD",
                                  "message":"Invalid current password."
                               }
                            ]
                         }
                        }
/accounts/{username}/forgotpassword:
      description: "Reset password for an account"
      uriParameters:
        username:
          type: "string"
      post:
        description: "Resets password for an account. It sends out an email notification\
          \ to the user to verify the password reset. The new password becomes effective\
          \ only after it has been verified by the user. It returns an error if an account\
          \ with the specified username does not exist OR the account has been DISABLED.\n\
          </br> The {username} is a value that uniquely identifies an account.\n"
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        responses:
          200:
            description: ""
            body:
              application/json:
                example: |
          404:
            body:
              application/json:
                example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ACCOUNT_NOT_FOUND",
                                   "message":"Account not found with username user@hslynk.com"
                                }
                             ]
                          }
                         }
/accounts/{accountid}/roles:
      put:
        description: "To assigne a role to user. If the role is already assigned nothing\
          \ will happen."
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        body:
          application/json:
            example: |
              {
                "roles":{
                    "role":[
                       {
                          "id":"6b5857d9-bc16-4706-acde-17be5d530631"
                       },
                       {
                          "id":"1ebd9476-600c-463f-8c3d-bf8accad472b"
                       }
                  ]
                 }
               }
        responses:
          200:
            body:
              application/json:
                example: |
          404:
            body:
              application/json:
               example: |
                       {
                         "errors":{
                            "error":[
                               {
                                  "code":"ACCOUNT_NOT_FOUND",
                                  "message":"Account not found with username user@hslynk.com"
                               }
                            ]
                         }
                        }
      /{roleid}:
        uriParameters:
          roleid:
            type: "string"
        delete:
          description: "To remove role from the user."
          headers:
            Authorization:
              type: "string"
              description: "Authorization request header should specify as HMISUserAuth\
                \ session_token={sessiontokenvalue}."
              example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
            X-HMIS-TrustedApp-Id:
              type: "string"
              description: "Trusted App id should be provide in this header."
              example: "MASTER_TRUSTED_APP"
          responses:
            200:
              body:
                application/json:
                  example: |
            404:
              body:
                application/json:
                  example: |
                            {
                              "errors":{
                                 "error":[
                                    {
                                       "code":"ACCOUNT_NOT_FOUND",
                                       "message":"Account not found with username user@hslynk.com"
                                    }
                                 ]
                              }
                             }
/profiles:
  get:
    description: "To get all Profiles"
    queryParameters:
      startIndex:
        type: "string"
        default: "0"
        required: false
      maxItems:
        type: "string"
        default: "30"
        required: false
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
           example: |
             {
               "profiles":{
                  "pagination":{
                     "from":0,
                     "returned":5,
                     "total":5,
                     "maximum":30,
                     "sort":{

                     }
                  },
                  "profile":[
                     {
                        "profileName":"Standard Profile",
                        "profileDescription":"Standard Profile",
                        "apiMethods":[

                        ],
                        "id":"004aed07-b4d4-4696-b8f6-1607f6f49bac"
                     },
                     {
                        "profileName":"Developer Profile",
                        "profileDescription":"Developer Profile",
                        "apiMethods":[

                        ],
                        "id":"1ebd9476-600c-463f-8c3d-bf8accad472b"
                     },
                     {
                        "profileName":"Super Admin Profile",
                        "profileDescription":"Super Admin Profile",
                        "apiMethods":[

                        ],
                        "id":"b67c38a1-2762-4393-b69b-41a0a11e6efc"
                     },
                     {
                        "profileName":"Profile Name 1461664017106",
                        "profileDescription":"Profile Desc 1461664017106",
                        "apiMethods":[

                        ],
                        "id":"3faedfc8-7692-411a-8157-a9cbde9fd9d1"
                     },
                     {
                        "profileName":"Customer Admin Profile",
                        "profileDescription":"Customer Admin Profile",
                        "apiMethods":[

                        ],
                        "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc"
                     }
                  ]
               }
             }
  post:
    description: "Create a new profile"
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    body:
      application/json:
        example:  |
                  {
                       "profile":{
                          "profileName":"HMIS Profile Name",
                          "profileDescription":"descriptrion",
                          "apiMethods":[
                             {
                                "id":"a7a316c4-c348-408c-ae6c-806d4cfe114a"
                             },
                             {
                                "id":"82500c87-0d4f-48dd-bbfa-9d4040100341"
                             }
                          ]
                       }
                    }
    responses:
      200:
        body:
          application/json:
           example: |
                   {
                        "profile":{
                          "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc",
                           "profileName":"HMIS Profile Name",
                           "profileDescription":"descriptrion",
                           "apiMethods":[
                              {
                                 "id":"a7a316c4-c348-408c-ae6c-806d4cfe114a"
                              },
                              {
                                 "id":"82500c87-0d4f-48dd-bbfa-9d4040100341"
                              }
                           ]
                        }
                     }
  /{profileId}:
    uriParameters:
      profileId:
        type: "string"
    put:
      description: "To Update A specific Profile."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      body:
        application/json:
          example:  |
                    {
                         "profile":{
                            "profileName":"HMIS Profile Name",
                            "profileDescription":"descriptrion",
                            "apiMethods":[
                               {
                                  "id":"a7a316c4-c348-408c-ae6c-806d4cfe114a"
                               },
                               {
                                  "id":"82500c87-0d4f-48dd-bbfa-9d4040100341"
                               }
                            ]
                         }
                      }
      responses:
        200:
          body:
            application/json:
             example: |
                         {
                              "profile":{
                                 "profileName":"HMIS Profile Name",
                                 "profileDescription":"descriptrion",
                                 "apiMethods":[
                                    {
                                       "id":"a7a316c4-c348-408c-ae6c-806d4cfe114a"
                                    },
                                    {
                                       "id":"82500c87-0d4f-48dd-bbfa-9d4040100341"
                                    }
                                 ]
                              }
                           }
        404:
          body:
            application/json:
             example: |
                       {
                         "errors":{
                            "error":[
                               {
                                  "code":"ERR_CODE_PROFILE_NOT_FOUND",
                                  "message":"Profile not found"
                               }
                            ]
                         }
                        }
    delete:
      description: "To Delete A specific Profile\n"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
             example: |
        404:
          body:
            application/json:
             example: |
                       {
                         "errors":{
                            "error":[
                               {
                                  "code":"ERR_CODE_PROFILE_NOT_FOUND",
                                  "message":"Profile not found"
                               }
                            ]
                         }
                        }
    get:
      description: "To get a Specific Profile Details"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
             example:  |
                     {
                          "profile":{
                            "id":"d78c38a1-2762-4393-b69b-41a0a11e6efc",
                             "profileName":"HMIS Profile Name",
                             "profileDescription":"descriptrion",
                             "apiMethods":[
                                {
                                   "id":"a7a316c4-c348-408c-ae6c-806d4cfe114a"
                                },
                                {
                                   "id":"82500c87-0d4f-48dd-bbfa-9d4040100341"
                                }
                             ]
                          }
                       }
        404:
          body:
           application/json:
            example: |
                      {
                        "errors":{
                           "error":[
                              {
                                 "code":"ERR_CODE_PROFILE_NOT_FOUND",
                                 "message":"Profile not found"
                              }
                           ]
                        }
                       }
/sharingrules:
  post:
    description: "Create a new sharing rule."
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
            type: "object"
      404:
        body:
          application/json:
            type: "object"
  /{sharingruleid}:
    uriParameters:
      sharingruleid:
        type: "string"
    put:
      description: "To update a specifc Sharing Rule"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
    delete:
      description: "To Delete A Specifc Sharing Rule"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
/roles:
  get:
    description: "To get All the roles."
    queryParameters:
      startIndex:
        type: "string"
        default: "0"
        required: false
      maxItems:
        type: "string"
        default: "30"
        required: false
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
           example: |
             {
                    "roles":{
                          "pagination":{
                          "from":0,
                          "returned":4,
                          "total":4,
                          "maximum":30,
                          "sort":{

                          }
                    },
                    "role":[
                              {
                                 "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                                 "roleName":"DEVELOPER",
                                 "roleDescription":"Developer Role"
                              },
                              {
                                 "id":"b67c38a1-2762-4393-b69b-41a0a11e6efd",
                                 "roleName":"CUSTADMIN",
                                 "roleDescription":"Customer Admin Role"
                              },
                              {
                                 "id":"6b5857d9-bc16-4706-acde-17be5d530631",
                                 "roleName":"STANDARD",
                                 "roleDescription":"Standard Role"
                              },
                              {
                                 "id":"b67c38a1-2762-4393-b69b-41a0a11e6efc",
                                 "roleName":"SUPERADMIN",
                                 "roleDescription":"Super Admin Role"
                              }
                        ]
                    }
              }
  post:
    description: "To create A new role"
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    body:
      application/json:
        example: |
                {
                   "role":{
                      "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                      "roleName":"DEVELOPER",
                      "roleDescription":"Developer Role"
                   }
                }
    responses:
      200:
        body:
          application/json:
            example: |
                        {
                           "role":{
                              "roleName":"DEVELOPER",
                              "roleDescription":"Developer Role"
                           }
                        }
  /{roleid}:
    uriParameters:
      roleid:
        type: "string"
    put:
      description: "To update a specific role"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      body:
        application/json:
          example: |
                    {
                       "role":{
                          "roleName":"DEVELOPER",
                          "roleDescription":"Developer Role"
                       }
                    }
      responses:
        200:
          body:
            application/json:
              example: |
                          {
                             "role":{
                                "roleName":"DEVELOPER",
                                "roleDescription":"Developer Role"
                             }
                          }
        404:
          body:
            application/json:
              example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ERR_CODE_ROLE_NOT_FOUND",
                                   "message":"Role not found"
                                }
                             ]
                          }
                         }
    delete:
      description: "To delete a Specific role"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              example: |
        404:
          body:
            application/json:
              example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ERR_CODE_ROLE_NOT_FOUND",
                                   "message":"Role not found"
                                }
                             ]
                          }
                         }
/permissionsets:
  post:
    description: "To create a new Permission Set."
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
            type: "object"
  /{permissionsetid}:
    uriParameters:
      permissionsetid:
        type: "string"
    put:
      description: "To update a Specific Permission Set"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
    delete:
      description: "To Delete a specific Permission Set"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
    get:
      description: "To get Details About a specific Permision Set"
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
  /{username}:
    uriParameters:
      username:
        type: "string"
    /permissionsetassignments:
      post:
        description: "To Assign a Permission to A user\n <b>Note:</b> /permissionset/hmisuser/assignPermissionSet\n"
        headers:
          Authorization:
            type: "string"
            description: "Authorization request header should specify as HMISUserAuth\
              \ session_token={sessiontokenvalue}."
            example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
          X-HMIS-TrustedApp-Id:
            type: "string"
            description: "Trusted App id should be provide in this header."
            example: "MASTER_TRUSTED_APP"
        responses:
          200:
            body:
              application/json:
                type: "object"
          404:
            body:
              application/json:
                type: "object"
/informationreleases:
  post:
    description: "To create a release information for a enrollment."
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
            type: "object"
      404:
        body:
          application/json:
            type: "object"
  /{enrollmentId}:
    uriParameters:
      enrollmentId:
        type: "string"
    put:
      description: "To update an enrollment's release of information."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
    delete:
      description: "To delete an enrollment's release of information."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
    get:
      description: "To get an enrollment's release of information."
      queryParameters:
        startIndex:
          type: "string"
          default: "0"
          required: false
        maxItems:
          type: "string"
          default: "30"
          required: false
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              type: "object"
        404:
          body:
            application/json:
              type: "object"
/projectgroups:
  post:
    description: "To create a new project group.\n"
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    body:
      application/json:
        example:
          {
             "projectgroup":{
                "projectGroupName":"PROJECT_GROUP_NAME",
                "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
             }
          }
    responses:
      200:
        body:
          application/json:
            example: |
                      {
                         "projectgroup":{
                            "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                            "projectGroupName":"PROJECT_GROUP_NAME",
                            "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
                         }
                      }
  get:
    description: "To retrive existing project groups."
    queryParameters:
      startIndex:
        type: "string"
        default: "0"
        required: false
      maxItems:
        type: "string"
        default: "30"
        required: false
    headers:
      Authorization:
        type: "string"
        description: "Authorization request header should specify as HMISUserAuth\
          \ session_token={sessiontokenvalue}."
        example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
      X-HMIS-TrustedApp-Id:
        type: "string"
        description: "Trusted App id should be provide in this header."
        example: "MASTER_TRUSTED_APP"
    responses:
      200:
        body:
          application/json:
           example: |
                   {
                     "projectgroups":{
                        "pagination":{
                           "from":0,
                           "returned":2,
                           "total":2,
                           "maximum":30,
                           "sort":{

                           }
                        },
                        "projectgroup":[
                           {
                              "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                              "projectGroupName":"PROJECT_GROUP_NAME",
                              "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
                           },
                           {
                              "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                              "projectGroupName":"PROJECT_GROUP_NAME2",
                              "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION2"
                           }
                        ]
                     }
                   }
  /{projectgroupid}:
    uriParameters:
      projectgroupid:
        type: "string"
    put:
      description: "To update existing project group. While updating project group,\
        \ api will remove all the assigned projects and add projects which are in new\
        \ request body."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      body:
        application/json:
          example:  |
                  {
                   "projectgroup":{
                      "projectGroupName":"PROJECT_GROUP_NAME",
                      "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
                   }
                  }
      responses:
        200:
          body:
            application/json:
             example: |
                       {
                        "projectgroup":{
                           "projectGroupName":"PROJECT_GROUP_NAME",
                           "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
                        }
                       }
        404:
          body:
            application/json:
              example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ERR_CODE_PROJECT_GROUP_NOT_FOUND",
                                   "message":"Project Group not found"
                                }
                             ]
                          }
                         }
    delete:
      description: "To remove existing project group."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              example: |
        404:
          body:
            application/json:
              example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ERR_CODE_PROJECT_GROUP_NOT_FOUND",
                                   "message":"Project Group not found"
                                }
                             ]
                          }
                         }
    get:
      description: "To retrieve selected project group."
      headers:
        Authorization:
          type: "string"
          description: "Authorization request header should specify as HMISUserAuth\
            \ session_token={sessiontokenvalue}."
          example: "HMISUserAuth session_token=956048930B39448A8B6ABEDF57BECFFC07E2628546F847149BD42D4BC3CFDC39"
        X-HMIS-TrustedApp-Id:
          type: "string"
          description: "Trusted App id should be provide in this header."
          example: "MASTER_TRUSTED_APP"
      responses:
        200:
          body:
            application/json:
              example: |
                      {
                         "projectgroup":{
                            "id":"1ebd9476-600c-463f-8c3d-bf8accad472b",
                            "projectGroupName":"PROJECT_GROUP_NAME",
                            "projectGroupDesc":"PROJECT_GROUP_DESCRIPTION"
                         }
                      }
        404:
          body:
            application/json:
              example: |
                        {
                          "errors":{
                             "error":[
                                {
                                   "code":"ERR_CODE_PROJECT_GROUP_NOT_FOUND",
                                   "message":"Project Group not found"
                                }
                             ]
                          }
                         }
